### ISSUE TITLE
HELP: Remote/Azure Server Database - ConnnectionString 

### ISSUE THREAD

**Issue by uniqueitmail** [DevExpress-Examples/XAF_how-to-change-connection-to-the-database-at-runtime-e1344#4]
> **REQUEST_TO: HELP _WANTED_**

ConnectionString  - remote database with MSSQL command please write in App.config
with current ConnectionString - Local to Remote/Azure  database.

#XAF_how-to-change-connection-to-the-database-at-runtime-e1344

**Remote Server Database Not Work: Solution Please of your project::**
`<add name="ConnectionString" connectionString="Integrated Security=false;Pooling=false;Data Source=161.151.141.253; User ID=sa;Password=1; Initial Catalog=RuntimeDbChooser" />`

Please write about Remote Database with MSSQL on App.config  - Inside will be E1344  - What am I wrong with this ConnectionString...

_Thank you._

**Comment by AndreyKozhevnikov** [comment]
Hello,
 
Connection strings in app.config (or web.config) files is a common .NET feature not related to XAF or DevExpress. If you face any difficulties with connecting your application to a database, refer to .NET documentation to learn how to configure your connection string.
Refer also to my answer here: [Update App.config by uniqueitmail · Pull Request #2 · DevExpress-Examples/XAF_how-to-change-connection-to-the-database-at-runtime-e1344](https://github.com/DevExpress-Examples/XAF_how-to-change-connection-to-the-database-at-runtime-e1344/pull/2#issuecomment-536857933)
 
Thanks,
Andrey
